# 1. Đại số tuyến tính

## 1.1. Số vô hướng (scalar)

Trong cuộc sống hàng ngày chúng ta sẽ gặp rất nhiều số vô hướng (scalar). Giá trị của tiền nhà tháng này mà bạn phải trả cho chủ nhà là một số vô hướng. Bạn vừa thực hiện một bài kiểm tra toán, bạn được 9 điểm thì điểm số này là một số vô hướng,.... Tóm lại số vô hướng là một con số cụ thể. Số vô hướng sẽ khác với biến số vì biến số có thể nhận nhiều giá trị trong khi số vô hướng chỉ nhận một giá trị duy nhất. Ví dụ, khi biểu diễn giá nhà $y$ theo diện tích $x$ theo phương trình $y=20x + 200$ thì các số  vô hướng là $20, 200$ và các biến là $x, y$.

Để khởi tạo một số vô hướng, chúng ta sẽ sử dụng tensor

In [2]:
import tensorflow as tf

a = tf.constant(20)
b = tf.constant(200)
print("diện tích x = 50 --> giá nhà y = a*50+b = ", a*50+b)

diện tích x = 50 --> giá nhà y = a*50+b =  tf.Tensor(1200, shape=(), dtype=int32)


Số vô hướng có thể được coi như hằng số trong một phương trình. Chúng ta có thể thực hiện các phép toán cộng/trừ/nhân/chia với số vô hướng như với hằng số.

## 1.2. Véc tơ

Véc tơ là một khái niệm cơ bản nhất của toán học. Chúng ta có thể coi véc tơ là một tập hợp nhiều giá trị của số vô hướng. Véc tơ thường biểu diễn một đại lượng cụ thể trên thực tiễn. Ví dụ như diện tích của các căn nhà là một véc tơ, số lượng phòng ngủ cũng là một véc tơ. Véc tơ có độ dài đặc trưng chính bằng số lượng các phần tử trong nó. Để khởi tạo một véc tơ, trong tensorflow chúng ta bao các giá trị của nó trong dấu ngoặc vuông.

In [3]:
x = tf.constant([1, 1.2, 1.5, 1.8, 2])
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1. , 1.2, 1.5, 1.8, 2. ], dtype=float32)>

Hoặc ta có thể khởi tạo từ numpy array.

In [4]:
import numpy as np
x = np.array([1, 1.2, 1.5, 1.8, 2])
tf.constant(x)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1. , 1.2, 1.5, 1.8, 2. ])>

In [5]:
x[0] = 10.1
x

array([10.1,  1.2,  1.5,  1.8,  2. ])

Tensorflow tách biệt giữa những đại lượng hằng số (cố định) và biến số (thay đổi trong quá trình huấn luyện). Để khởi tạo một biến số trong tensorflow thì chúng ta sử dụng hàm `tf.Variable()`.

In [6]:
w = tf.Variable([1, 1.2, 1.5, 1.8, 2])
w

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([1. , 1.2, 1.5, 1.8, 2. ], dtype=float32)>

### 1.2.1. Các thuộc tính của véc tơ

Một véc tơ sẽ có độ dài và định dạng dữ liệu xác định. Ngoài ra nếu coi một biến số là một véc tơ thì trong thống kê mô tả chúng ta sẽ quan tâm tới tổng, trung bình, phương sai, giá trị lớn nhất, nhỏ nhất.

In [7]:
# Độ dài
print("length of vector: ", x.shape) # or len(x)

# Định dạng của véc tơ
print("vector type: ", x.dtype)

# Tổng của các phần tử
print("sum of vector: ", tf.math.reduce_sum(x))

# Trung bình các phần tử
print("mean of vector: ", tf.math.reduce_mean(x))

# Giá trị nhỏ nhất
print("min of vector: ", tf.math.reduce_min(x))

# Giá trị lớn nhất
print("max of vector: ", tf.math.reduce_max(x))

length of vector:  (5,)
vector type:  float64
sum of vector:  tf.Tensor(16.6, shape=(), dtype=float64)
mean of vector:  tf.Tensor(3.3200000000000003, shape=(), dtype=float64)
min of vector:  tf.Tensor(1.2, shape=(), dtype=float64)
max of vector:  tf.Tensor(10.1, shape=(), dtype=float64)


### 1.2.2. Các phép tính trên véc tơ

Chúng ta có thể thực hiện các phép tính trên véc tơ như phép cộng, trừ, tích vô hướng, tích có hướng giữa hai véc tơ.. Lưu ý là chúng phải có cùng độ dài. Trong khuôn khổ cuốn sách này, các véc tơ sẽ được ký hiệu là một ký tự chữ thường in đậm như $\mathbf{x}, \mathbf{y}, \mathbf{z}$. Ngoài ra $\mathbf{x}\in \mathbb{R}^{n}$ là véc tơ số thực có độ dài $n$.

In [8]:
x = tf.constant([1, 2, 1.5, 1.8, 1.9])
y = tf.constant([1.1, 2.2, 1.2, 1.6, 1.7])
print("x + y: ", x + y)
print("x - y: ", x - y)
print("x * y: ", x * y)
print("x / y: ", x / y)

x + y:  tf.Tensor([2.1 4.2 2.7 3.4 3.6], shape=(5,), dtype=float32)
x - y:  tf.Tensor([-0.10000002 -0.20000005  0.29999995  0.19999993  0.19999993], shape=(5,), dtype=float32)
x * y:  tf.Tensor([1.1       4.4       1.8000001 2.8799999 3.23     ], shape=(5,), dtype=float32)
x / y:  tf.Tensor([0.9090909 0.9090909 1.25      1.125     1.117647 ], shape=(5,), dtype=float32)


Véc tơ có thể thực hiện các phép cộng, trừ, nhân, chia với một số vô hướng. Giá trị thu được là một véc tơ cùng kích thước mà mỗi phần tử của nó là kết quả được thực hiện trên từng phần tử của véc tơ với số vô hướng đó.

In [9]:
x = tf.constant([1, 2, 1.5, 1.8, 1.9])
print("x + 5: ", x + 5)
print("x - 5: ", x - 5)
print("x * 5: ", x * 5)

x + 5:  tf.Tensor([6.  7.  6.5 6.8 6.9], shape=(5,), dtype=float32)
x - 5:  tf.Tensor([-4.  -3.  -3.5 -3.2 -3.1], shape=(5,), dtype=float32)
x * 5:  tf.Tensor([ 5.  10.   7.5  9.   9.5], shape=(5,), dtype=float32)


## 1.3. Ma trận

Véc tơ là đại lượng một chiều nên nó chỉ có thể biểu diễn cho một biến. Trong trường hợp chúng ta cần biểu diễn cho nhiều biến thì sẽ cần tới đại lượng hai chiều là ma trận. Ma trận được kí hiệu bởi một chữ cái in đậm $\mathbf{A}$. Kí hiệu $\mathbf{A} \in \mathbb{R}^{m\times n}$ là một ma trận số thực có $m$ dòng và $n$ cột:

\begin{split}\mathbf{A}=\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \\ \end{bmatrix}.\end{split}

Để xác định một phần tử bất kỳ thuộc dòng thứ $i$, cột thứ $j$ của ma trận $\mathbf{A}$ ta ký hiệu chúng là $\mathbf{A}_{ij}$. Véc tơ dòng thứ $i$ sẽ là $\mathbf{A}_{i:}$ và véc tơ cột thứ $j$ sẽ là $\mathbf{A}_{:j}$. Để đơn giản hoá ta qui ước $\mathbf{A}_{j}$ là véc tơ cột $j$ và $\mathbf{A}^{(i)}$ là véc tơ dòng $i$.

Để khởi tạo ma trận trên tensorflow thì chúng ta chỉ cần khai báo các véc tơ dòng của ma trận.

In [10]:
A=tf.constant([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]], dtype = tf.float32)
A

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)>

In [11]:
A=tf.Variable([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]], dtype = tf.float32)

Đối số `dtype` được sử dụng để khai báo kiểu dữ liệu của các phần tử trong tensor. Thông thường chúng ta có các kiể dữ liệu `int, float, double`. Kiểu `int` là số nguyên, `float` là số thập phân, `double` cũng là kiểu số thập phân nhưng có miền giá trị lớn hơn so với float.

### 1.3.1. Các ma trận đặc biệt

* Ma trận vuông: Ma trận vuông là ma trận có số dòng bằng số cột. Ma trận vuông rất quan trọng vì khi tìm nghiệm cho hệ phương trình, từ ma trận vuông ta có thể chuyển sang ma trận tam giác. Ma trận vuông cũng là ma trận có thể tính được giá trị định thức. Một ma trận $\mathbf{A} \in \mathbb{R}^{m \times n}$ vuông nếu $m=n$.



* Ma trận đơn vị: Là ma trận có đường chéo chính bằng 1, các phần tử còn lại bằng $0$. Ví dụ ma trận đơn vị kích thước $3 \times 3$ được ký hiệu là $\mathbf{I}_3$ có gía trị là:

$$\begin{split}\mathbf{I}_3=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\end{split}$$

Tóm lại, $\mathbf{A}$ là ma trận đơn vị nếu nó là ma trận vuông và $a_{ij} = 1$ nếu $i=j$ và $a_{ij} = 0$ nếu $i \neq j$.



In [12]:
# Khởi tạo ma trận đơn vị với kích thước là 3x3
I3 = tf.eye(3, dtype=tf.float32)
I3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

* Ma trận một: Ma trận một là ma trận gồm toàn bộ các phần tử có kích thước là 1. Hàm `torch.ones()` được sử dụng để khởi tạo ma trận một.

In [13]:
tf.ones((3, 3), dtype=tf.int8)

<tf.Tensor: shape=(3, 3), dtype=int8, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)>

In [14]:
tf.ones(3, dtype=tf.int8)

<tf.Tensor: shape=(3,), dtype=int8, numpy=array([1, 1, 1], dtype=int8)>


* Ma trận đường chéo: Là ma trận có các phần tử trên đường chéo chính khác 0 và các phần tử còn lại bằng 0. Ví dụ về ma trận đường chéo:


$$\begin{split}\mathbf{A}=
\begin{bmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3
\end{bmatrix}
\end{split}$$

Để khởi tạo ma trận đường chéo trước tiên ta cần khởi tạo véc tơ đường chéo và sau đó truyền véc tơ này vào hàm `torch.diag()`

In [15]:
# Khởi tạo ma trận đường chéo
x = tf.constant([1, 2, 3], dtype=tf.float32)
tf.linalg.diag(x) # diagonal

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]], dtype=float32)>



* Ma trận chuyển vị: $\mathbf{B}$ là ma trận chuyển vị của $\mathbf{A}$ nếu $b_{ij} = a_{ji}$ với mọi $i, j$. Dễ hiểu hơn, tức là mọi dòng của ma trận $A$ sẽ là cột của ma trận $\mathbf{B}$. Ví dụ:

$$\begin{split}\mathbf{A}=
\begin{bmatrix}
1 & 2 & 3 \\
3 & 2 & 1
\end{bmatrix}
\end{split}, \begin{split}\mathbf{B}=
\begin{bmatrix}
1 & 3 \\
2 & 2 \\
3 & 1\end{bmatrix}
\end{split}$$


Ký hiệu chuyển vị của ma trận $\mathbf{A}$ là $\mathbf{A}^{\intercal}$

In [20]:
# Khởi tạo ma trận A kích thước 2 x 3
A = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
A

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [22]:
# Chuyển vị của ma trận A
tf.transpose(A)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [18]:
import numpy as np
A1 = np.array([[1, 2], [3, 4], [5, 6]])
A1.T

array([[1, 3, 5],
       [2, 4, 6]])

In [47]:
tf.experimental.numpy.experimental_enable_numpy_behavior()
A.T

<tf.Tensor: shape=(4, 3, 2), dtype=float32, numpy=
array([[[ 1.5935962 ,  0.20924737],
        [ 2.2947032 , -0.3333056 ],
        [ 1.6322331 ,  0.8270561 ]],

       [[ 1.5372411 ,  0.5536078 ],
        [-0.22455435, -0.10403281],
        [-1.3672563 , -0.64242214]],

       [[ 0.8170439 , -0.23429365],
        [ 0.06097581, -1.8554885 ],
        [ 1.0892    , -0.6557203 ]],

       [[ 1.9598553 , -0.562763  ],
        [ 2.1433766 , -2.748895  ],
        [ 1.3691394 , -0.3521034 ]]], dtype=float32)>

### 1.3.2. Các thuộc tính của ma trận

Một ma trận được đặc trưng bởi dòng và cột.

In [23]:
import tensorflow as tf
A = tf.constant([[1, 2, 3],
                 [3, 2, 1]])

# shape của matrix A
A.shape

TensorShape([2, 3])

Định dạng biến của ma trận. Thông thường chúng ta có các kiểu `int, float, double, complex, object`.

In [24]:
A.dtype

tf.int32

Số lượng các chiều của ma trận

In [25]:
A.ndim # number of dimensions

2

### 1.3.3. Các phép tính trên ma trận

Hai ma trận có cùng kích thước chúng ta có thể thực hiện các phép cộng, trừ, tích hadamard (hoặc element-wise). Ma trận thu được cũng có cùng kích thước và các phần tử của nó được tính dựa trên các phần tử có cùng vị trí trên cả hai ma trận $\mathbf{A}$ và $\mathbf{B}$.

**Tích hadamard hoặc element-wise**
$$
\begin{split}\mathbf{A} \odot \mathbf{B} =
\begin{bmatrix}
    a_{11}  b_{11} & a_{12}  b_{12} & \dots  & a_{1n}  b_{1n} \\
    a_{21}  b_{21} & a_{22}  b_{22} & \dots  & a_{2n}  b_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1}  b_{m1} & a_{m2}  b_{m2} & \dots  & a_{mn}  b_{mn}
\end{bmatrix}\end{split}
$$

Tức là $$c_{ij} = a_{ij}*b_{ij}$$

Trên pytorch chúng ta có thể tính tích hadamard của hai ma trận đơn giản như sau:

In [26]:
import tensorflow as tf
A = tf.constant([[1, 2, 3],
                 [3, 2, 1]])

B = tf.constant([[2, 1, 2],
                 [1, 3, 0]])

A*B

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 6],
       [3, 6, 0]], dtype=int32)>

Tương tự với các phép cộng và trừ

In [27]:
print("A-B: \n", A-B)
print("A+B: \n", A+B)

A-B: 
 tf.Tensor(
[[-1  1  1]
 [ 2 -1  1]], shape=(2, 3), dtype=int32)
A+B: 
 tf.Tensor(
[[3 3 5]
 [4 5 1]], shape=(2, 3), dtype=int32)


**Tích thông thường (dot product)**: Tích thông thường giữa hai ma trận $\mathbf{A}$ có kích thước $m \times n$ và $\mathbf{B}$ có kích thước $n \times p$ là một ma trận có kích thước $m \times p$. Ma trận output $\mathbf{C}$ có giá trị tại phần tử $c_{ij} = \mathbf{A}^{(i)} \mathbf{B}_{j}$ (dòng thứ $i$ của ma trận $\mathbf{A}$ nhân với cột thứ $j$ của ma trận $\mathbf{B}$).

$$
\begin{split}\mathbf{A}_{m \times n} \mathbf{B}_{n \times p} =
\begin{bmatrix}
    \mathbf{A}^{(1)}  \mathbf{B}_{1} & \mathbf{A}^{(1)}  \mathbf{B}_{2} & \dots  & \mathbf{A}^{(1)}  \mathbf{B}_{p} \\
    \mathbf{A}^{(2)}  \mathbf{B}_{1} & \mathbf{A}^{(2)}  \mathbf{B}_{2} & \dots  & \mathbf{A}^{(2)}  \mathbf{B}_{p} \\
    \vdots & \vdots & \ddots & \vdots \\
    \mathbf{A}^{(m)}  \mathbf{B}_{1} & \mathbf{A}^{(m)}  \mathbf{B}_{2} & \dots  & \mathbf{A}^{(m)}  \mathbf{B}_{p} \\
\end{bmatrix}\end{split}_{m \times p}
$$

Chắc các bạn còn nhớ $\mathbf{A}^{(i)}$ là véc tơ dòng và $\mathbf{A}_{j}$ là véc tơ cột.


In [28]:
import tensorflow as tf
A = tf.constant([[1, 2, 3],
                 [3, 2, 1]])

B = tf.constant([[2, 1],
                 [1, 3],
                 [1, 1]])

A@B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 9, 10]], dtype=int32)>

Hoặc sử dụng hàm `tf.matmul()`

In [29]:
tf.matmul(A, B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 9, 10]], dtype=int32)>

In [30]:
np.array(A)

array([[1, 2, 3],
       [3, 2, 1]], dtype=int32)

In [31]:
tf.math.reduce_sum(A, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 6], dtype=int32)>

### 1.3.4. Truy cập thành phần

Chúng ta có thể truy cập vào các thành phần của ma trận $\mathbf{A}$ dựa theo các chỉ số slice index. Chúng ta có thể tổng hợp kiến thức về truy cập thành phần trong bản sau:

| Cú pháp      | Mô tả |
| ----------- | ----------- |
| :n      | lấy n index đầu tiên từ [0, 1, ..., n-1]       |
| -n:   | lấy n index cuối cùng từ [len-n, ..., len-1]        |
| i:j   | lấy các index từ [i, i+1, ..., j-1]        |
| ::2   | lấy các index chẵn liên tiếp [0, 2, 4 ..., int(len/2)*2]        |
| ::k   | lấy các index cách đều và chia hết cho k một cách liên tiếp [0, k, 2k, ..., int(len/k)*k]        |
| :   | lấy toàn bộ index        |

In [32]:
import tensorflow as tf
A = tf.constant([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]], dtype=tf.float32)

# Truy cập ma trận con từ 2 dòng đầu tiên và 2 cột đầu tiên.

In [33]:
A[-2:, :2]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 5.],
       [7., 8.]], dtype=float32)>

In [34]:
# Truy cập véc tơ con từ dòng thứ 2 và 2 cột cuối cùng.
print(A[2, -2:])

# Hoặc
A[2:3, -2:]

tf.Tensor([8. 9.], shape=(2,), dtype=float32)


<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[8., 9.]], dtype=float32)>

In [35]:
# Truy cập ma trận có các dòng chẵn
A[::2, :]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [7., 8., 9.]], dtype=float32)>

In [36]:
A

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [37]:
# Truy cập một index cụ thể ví dụ dòng 0, 2 của ma trận
tf.gather(A, indices=[[0, 2]], axis=0)

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [7., 8., 9.]]], dtype=float32)>

In [38]:
tf.gather(A, indices=[[0, 2]], axis=1)

<tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[1., 3.]],

       [[4., 6.]],

       [[7., 9.]]], dtype=float32)>

## 1.4. Tensor

Tensor là một định dạng đặc biệt được sáng tạo bởi google. Nó tổng quát hơn so với ma trận vì có thể biểu diễn được các không gian với số chiều tuỳ ý. Chẳng hạn trong xử lý ảnh chúng ta có một bức ảnh với kích thước là $W \times H \times C$ lần lượt $W, H, C$ là chiều _width, height và channels_. Thông thường $C = 1$ hoặc $3$ tuỳ theo ảnh là ảnh xám hay ảnh màu. Trong huấn luyện mô hình phân loại ảnh thì các đầu vào được kết hợp theo mini-batch nên sẽ có thêm một chiều về batch_size. Do đó input có kích thước là $N \times W \times H \times C$.

### 1.4.1. Các thuộc tính của tensor

Một tensor được đặc trưng bởi kích thước các chiều, số lượng chiều, định dạng dữ liệu của tensor.

In [39]:
A = tf.constant([[[1, 2, 3],
                  [3, 2, 1]],
                  [[2, 1, 2],
                  [1, 3, 0]]])

# Kích thước của tensor
print("shape of A: " , A.shape)

# Số chiều
print("total dim: ", A.ndim)

# Định dạng dữ liệu
print("dtype: ", A.dtype)

shape of A:  (2, 2, 3)
total dim:  3
dtype:  <dtype: 'int32'>


### 1.4.2. Các phép tính trên tensor

**Tích thông thường giữa 2 tensors**: Nếu tensor $\mathbf{A}$ có kích thước $m \times n \times p$ và tensor $\mathbf{B}$ có kích thước $m \times p \times q$ thì tích giữa chúng có kích thước là $m \times n \times q$. Trên python chúng ta sử dụng ký hiệu `@` để đại diện cho tích thông thường (`dot product`).


In [40]:
import tensorflow as tf

A = tf.random.normal([2, 3, 4])
B = tf.random.normal([2, 4, 2])

# Tích giữa 2 tensor
(A@B).shape

TensorShape([2, 3, 2])

In [41]:
print(A)

tf.Tensor(
[[[-0.5540104  -1.2004923   0.4710707  -0.7381595 ]
  [-0.8205614  -1.743336    0.1455615  -1.2226577 ]
  [ 0.36261556  0.88347644  0.35773814  0.905317  ]]

 [[ 0.77009964 -0.75521266 -0.02420638 -0.6624944 ]
  [-1.3234785   0.13318525 -1.103589   -0.65816927]
  [-1.6658777   3.3044386   0.12632677 -1.0415176 ]]], shape=(2, 3, 4), dtype=float32)


Ngoài ra chúng ta có thể tính **tích hadamard giữa 2 tensors** $\mathbf{A}$ và $\mathbf{B}$ được ký hiệu bằng dấu `*` như sau:

In [46]:
import tensorflow as tf

A = tf.random.normal([2, 3, 4])
B = tf.random.normal([2, 3, 4])

# Tích hadamard giữa 2 tensor
(A*B).shape

TensorShape([2, 3, 4])

Chúng ta cũng có thể thực hiện các phép cộng, trừ giữa các tensor cùng kích thước.

In [43]:
# Phép cộng
(A+B).shape

TensorShape([2, 3, 4])

In [44]:
# Phép trừ
(A-B).shape

TensorShape([2, 3, 4])

**Truy cập thành phần**: Để truy cập vào một mảng thành phần của $\mathbf{A}$ chúng ta sẽ cần khai báo vị trí indices của chúng trên mỗi chiều của ma trận $\mathbf{A}$. Cách truy cập cũng hoàn toàn tương tự như đối với ma trận.

In [48]:
import tensorflow as tf

# Khởi tạo ma trận A kích thước m, n, p = 2, 3, 4
A = tf.random.normal([2, 3, 4])

# Truy cập ma trận đầu tiên
A[0, :, :]

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.06390144,  0.79118645,  0.98875344,  0.34866816],
       [-0.9742501 , -0.9606169 ,  0.43085876,  2.076385  ],
       [ 0.79451287, -0.50410336, -1.8802645 ,  0.9638247 ]],
      dtype=float32)>

In [49]:
A[:1, :, :]

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[ 0.06390144,  0.79118645,  0.98875344,  0.34866816],
        [-0.9742501 , -0.9606169 ,  0.43085876,  2.076385  ],
        [ 0.79451287, -0.50410336, -1.8802645 ,  0.9638247 ]]],
      dtype=float32)>

In [50]:
# Truy cập ma trận đầu tiên và chỉ lấy dòng từ 1 tới 3
A[0][1:3, :]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.9742501 , -0.9606169 ,  0.43085876,  2.076385  ],
       [ 0.79451287, -0.50410336, -1.8802645 ,  0.9638247 ]],
      dtype=float32)>

In [51]:
# Truy cập tương ứng với các chiều m, n, p lần lượt index đầu tiên, 2 index đầu tiên, và index thứ 3.
A[:1, :2, 3]

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.34866816, 2.076385  ]], dtype=float32)>

## 1.5. Tích giữa một ma trận với véc tơ

Bản chất của phép nhân một ma trận với một véc tơ là một **phép biến hình**. Giả sử bạn có ma trận $\mathbf{A} \in \mathbb{R}^{m \times n}$ và véc tơ $\mathbf{x} \in \mathbb{R}^{n}$. Khi đó tích giữa ma trận $\mathbf{A}$ với véc tơ $\mathbf{x}$ là một véc tơ $\mathbf{y}$ có kích thước mới là $\mathbf{y} \in \mathbb{R}^{m}$.

$$\mathbf{A}\mathbf{x} =
\begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix} \mathbf{x} = \begin{bmatrix}
\mathbf{a}^\top_{1} \mathbf{x} \\
\mathbf{a}^\top_{2} \mathbf{x} \\
\vdots \\
\mathbf{a}^\top_m \mathbf{x} \\
\end{bmatrix} = \begin{bmatrix}
y_1 \\
y_2 \\
\vdots \\
y_m
\end{bmatrix} = \mathbf{y}$$

Như vậy thông qua ma trận $\mathbf{A}$ chúng ta đã biến đổi véc tơ $\mathbf{x}$ từ không gian $n$ chiều sang véc tơ $\mathbf{y}$ trong không gian $m$ chiều. Đây là một định lý rất quan trọng vì bạn sẽ gặp nó thường xuyên trong mạng nơ ron để giảm chiều dữ liệu, trong phân tích suy biến, trong phép xoay ảnh và đặc biệt nhất là trong hồi qui tuyến tính.

Giả sử bạn đã biết được các biến đầu vào gồm: diện tích và số phòng ngủ như các dòng của ma trận bên dưới:



In [52]:
import tensorflow as tf

X = tf.constant([[100, 120, 80, 90, 105, 95],
                  [2, 3, 2, 2, 3, 2]])


Và hệ số hồi qui tương ứng với với chúng lần lượt là $\mathbf{w} = (10, 100)$. Khi đó giá nhà có thể được ước lượng bằng tích $\mathbf{y} = \mathbf{X}^{\top}\mathbf{w}$


In [53]:
w = tf.constant([[10], [100]])
y = tf.transpose(X)@w
y

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1200],
       [1500],
       [1000],
       [1100],
       [1350],
       [1150]], dtype=int32)>

Cách sử dụng hàm `tf.transpose()` như trên là tương đối dài và khó hiểu. Để sử dụng các tính toán như đối với `array matrix` trên `numpy` chúng ta sử dụng configuration như sau:

In [54]:
from tensorflow.python.ops.numpy_ops import np_config
np_config.enable_numpy_behavior()

Khi đó cách triển khai các toán tử hoàn toàn như numpy

In [55]:
y = X.T@w
y

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1200],
       [1500],
       [1000],
       [1100],
       [1350],
       [1150]], dtype=int32)>

## 1.6. Tích vô hướng (inner product)

Tích vô hướng giữa hai véc tơ $\mathbf{x}, \mathbf{y} \in \mathbb{R}^{d}$ có cùng kích thước là một số vô hướng được ký hiệu là $\langle \mathbf{x}, \mathbf{y} \rangle$ hoặc $\mathbf{x}^{\top}\mathbf{y}$ có công thức như sau:

$$\langle \mathbf{x}, \mathbf{y} \rangle = \sum_{i=1}^{d} x_i y_i$$

In [56]:
import tensorflow as tf

x = tf.constant([1, 2, 3])
y = tf.constant([2, 3, 4])

tf.reduce_sum(tf.multiply(x, y))

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [57]:
tf.reduce_sum(x*y)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [58]:
# Hoặc
tf.tensordot(x, y, 1)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

Tích vô hướng rất quan trọng. Đây cũng là lý do mà tôi phải tách chúng thành một mục riêng. Bạn có thể bắt gặp tích vô hướng rất nhiều trong machine learning. Bên dưới là một số tình huống thường gặp:

- Tích vô hướng có thể được sử dụng để tính giá trị ước lượng của phương trình hồi qui tuyến tính. Ví dụ nếu bạn biết giá nhà được biểu diễn theo diện tích $x_1$ và số phòng ngủ $x_2$ theo công thức:

$$y=20x_1 + 10x_2+ 200$$

Thì một cách khái quát bạn có thể ước lượng $y$ theo tích vô hướng giữa véc tơ đầu vào $\mathbf{x}^{\top} = (x_1, x_2, 1)$ và véc tơ hệ số $\mathbf{w} = (20, 10, 200)$ như sau:

$$\hat{y} = \mathbf{x}^{\top}\mathbf{w}$$

- Tích vô hướng cũng được sử dụng để tính trung bình có trọng số của $\mathbf{x}$:

$$\bar{\mathbf{x}} = \sum_{i=1}^{n} x_i q_i= \mathbf{x}^{\top}\mathbf{q}$$
với $\sum_{i=1}^{n} q_i= 1$

- Ngoài ra, chắc hẳn bạn còn nhớ cách tính cos giữa hai véc tơ $\mathbf{x}$ và $\mathbf{y}$ sẽ bằng tích vô hướng giữa hai véc tơ được chuẩn hoá theo norm chuẩn bậc 2.

$$\cos({\mathbf{x}, \mathbf{y}}) = \frac{\sum_{i=1}^{d} x_i y_i}{ \sqrt{\sum_{i=1}^{d} x_i^2} \sqrt{\sum_{i=1}^d y_i^2}}= \frac{\langle \mathbf{x}, \mathbf{y} \rangle}{\mathbf{||x||_2}\mathbf{||y||_2}}$$

Khái niệm về norm chuẩn bậc 2 cũng là một kiến thức rất quan trọng. Mình sẽ giúp các bạn tìm hiểu bên dưới.



## 1.7. Khái niệm chuẩn

Chuẩn là một độ đo trên véc tơ véc tơ hoặc ma trận. Một hàm
$f(\mathbf{x})$ là một phép ánh xạ từ véc tơ sang một đại lượng vô hướng $\mathbb{R}^{d} \mapsto \mathbb{R}$ nếu nó thoả mãn các tính chất.

1. Tính chất scale:

$$\alpha f(\mathbf{x}) = f(\alpha\mathbf{x})$$

Như vậy khi bạn phóng đại lên véc tơ $\alpha$ lần thì giá trị chuẩn của nó cũng phóng đại lên $\alpha$ lần.

2. Bất đẳng thức tam giác:

$$f(\mathbf{x} + \mathbf{y}) \leq f(\mathbf{x}) + f(
  \mathbf{y}
)$$

Nếu ta coi $\mathbf{x}$ như là véc tơ cạnh và $f(\mathbf{x})$ như là độ dài cạnh của một tam giác thì $f(\mathbf{x}), f(\mathbf{y})$ là độ dài của 2 cạnh bất kỳ và tổng của chúng sẽ lớn hơn độ dài cạnh còn lại $f(\mathbf{x} + \mathbf{y})$.

3. Tính chất không âm:

$$f(\mathbf{x}) \geq 0, \forall \mathbf{x}$$

Trong machine learning các bạn sẽ thường xuyên gặp một số chuẩn chính là chuẩn bậc 2

$$L_{2} = \|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n \left|x_i \right|^2 }$$



In [59]:
import tensorflow as tf
x = tf.random.normal([10])
tf.linalg.norm(x, ord=2)

<tf.Tensor: shape=(), dtype=float32, numpy=3.3940508365631104>

In [60]:
tf.linalg.norm(x, ord=1)

<tf.Tensor: shape=(), dtype=float32, numpy=8.599555969238281>

Ta nhận thấy hàm MSE đo lường sai số giữa giá trị dự báo và thực tế trong phương trình hồi qui tuyến tính cũng là một dạng chuẩn bậc 2.



Chuẩn bậc 1:

$$L_{1} = \|\mathbf{x}\|_1 = \sum_{i=1}^n \left|x_i \right| $$


In [ ]:
print(tf.linalg.norm(x, ord=1))
# hoặc
tf.reduce_sum(tf.abs(x))

tf.Tensor(6.6857586, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=6.6857586>

Trong hồi qui tuyến tính thì chuẩn bậc 1 đo lường sai số tuyệt đối giữa giá trị dự báo và giá trị thực tế còn chuẩn bậc 2 thường được sử dụng như hàm mất mát. Các chuẩn bậc 1 và bậc 2 cón được áp dụng lên các véc tơ trọng số và thêm vào hàm mất mát như thành phần điều chuẩn (_regularization term_) nhằm kiểm soát độ lớn của hệ số ước lượng và độ phức tạp của mô hình hồi qui. Xem thêm [hồi qui Ridge và Lasso](https://phamdinhkhanh.github.io/deepai-book/ch_ml/index_RidgedRegression.html).

Cả hai chuẩn trên đều là trường hợp cụ thể của chuẩn bậc $p$ (ký hiệu $L_{p}$) tổng quát hơn có công thức như sau:

$$L_{p} = \|\mathbf{x}\|_p = \left(\sum_{i=1}^n \left|x_i \right|^p \right)^{1/p}$$

Để cả 3 điều kiện về chuẩn được thoả mãn thì chúng ta cần có $p \geq 1$.

In [ ]:
# chuẩn p bất kỳ >= 1, chẳng hạn p=1.5
tf.linalg.norm(x, ord=1.5)

<tf.Tensor: shape=(), dtype=float32, numpy=3.4901347>

## 1.8. Trace của ma trận

Trace của một ma trận là tổng các phần tử nằm trên đường chéo chính của ma trận đó.


In [ ]:
import tensorflow as tf
A = tf.constant([[1, 2, 3],
                  [3, 2, 1],
                  [4, 2, 2]], dtype=tf.float32)

# Tính trace của ma trận
tf.linalg.trace(A)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

## 1.9. Định thức của ma trận

Định thức của một ma trận $\mathbf{A}$ vuông:

$$\begin{split}\mathbf{A}=\begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\dots & \dots & \ddots & \dots \\
a_{n1} & a_{n2} & \dots & a_{nn} \\
\end{bmatrix}\end{split}$$

có giá trị:

$$\det(\mathbf{A})= \sum_{(\sigma_1, \sigma_2, \dots, \sigma_n) \in \mathcal{S}} \text{sgn}(\sigma) a_{1\sigma_1}a_{2\sigma_2}\cdots a_{n\sigma_n}$$

Trong đó $\sigma=(\sigma_1, \sigma_2, \dots, \sigma_n)$ là một phép hoán vị các thành phần của tập hợp $n$ số tự nhiên đầu tiên $O = \{1, 2, \dots, n\}$. Tập hợp tất cả các hoán vị của $n$ số tự nhiên này còn được kí hiệu là $\mathcal{S}$. Hàm $\text{sgn}(\sigma)$ là một hàm nhận hai gía trị $\{1, -1\}$. Nếu số lần hoán vị $\sigma$ để biến đổi trở về tập $O$ là chẵn thì nhận gía trị $1$ và lẻ thì nhận giá trị $-1$.


In [ ]:
import tensorflow as tf

A = tf.constant([[1, 2],
                 [3, 4]], dtype=tf.float32)

# Định thức của ma trận
tf.linalg.det(A)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

# 2. Tóm tắt

Như vậy qua chương này mình đã hướng dẫn cho các bạn các kiến thức bản nhất trong đại số tuyến tính. Bao gồm:

1. Các khái niệm: Số vô hướng, véc tơ, ma trận, tensor kèm theo thuộc tính của chúng.
2. Các phép tính cộng, trừ, nhân ma trận, nhân véc tơ, nhân ma trận với véc tơ.
3. Khái niệm về chuẩn và ý nghĩa của chúng trong vai trò một độ đo đối với véc tơ.

Đây là những kiến thức nền tảng nhưng rất quan trọng mà bạn đọc cần nắm vững trước khi học sâu về AI.